name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./example-app

    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "${{ matrix.python-version }}"

    - name: Install Poetry Action
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: |
        poetry install --no-root

    - name: Parallel Jobs
      run: echo "Running lint, security, and formatter in parallel"

    - name: Lint
      run: |
        poetry run task lint

    - name: Security
      run: |
        poetry run task security

    - name: Formatter
      run: |
        poetry run task formatter
